config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: 'welcome#index'
    get 'login', to: 'devise/sessions#new'
  end
  resources :bars, except: [:destroy] do
    resources :comments
    resources :days
  end
  resources :bars do
    member do
      put "like", to: "bars#upvote"
      put "dislike", to: "bars#downvote"
    end
  end
end

app/models/bar.rb
class Bar < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments
  has_many :days

  validates :user, presence: true
  validates :name, presence: true, uniqueness: true
  validates :location, presence: true
  validates :address, presence: true


  def upvotes_score
    self.get_upvotes.size
  end

  def downvotes_score
    (self.get_downvotes.size) * -1
  end

  def self.popular_times(bars)
    n = 0

    bars.each {
                |bar|
                bar_id = bar.id
                unless Bar.have_today?(bar_id)
                query = bar.popular_query
                Bar.get_pop_page(bar_id, query)
                end
                bar.bar_img = "bar#{n}"
                n += 1
    }
  end

  def self.have_today?(bar_id)
    @today = Time.now.strftime("%A")
    Day.where(bar_id: bar_id).pluck(:day).include?(@today)
  end

  def self.get_pop_page(bar_id, query)
    pop_times = []
    agent = Mechanize.new { |agent| agent.user_agent_alias = "Mac Safari" }
    agent.get(query).body
    hours_open = agent.page.search("span[@class='_Map']").text.split('–')
    open_hours = DateTime.parse(hours_open[0]).strftime("%H").to_i
    popularity = agent.page.search("div[@class='lubh-bar']")
    popularity.map { |pop| pop_times << pop.attributes["style"].value.scan(/\d+/)[0] }
    Bar.assign_pop_times(open_hours, pop_times, bar_id)
  end

  def self.assign_pop_times(open_hours, pop_times, bar_id)

    closed_hours = 0
    today = Time.now.strftime("%A")
    while closed_hours < 24
      day = Day.new
      day.attributes = { :day => today, :hour => closed_hours, :popularity => 0, :bar_id => bar_id }
      day.save
      closed_hours += 1
    end
    pop_times.each {
                    |pop|
                    Bar.assign_hour(open_hours, today, pop, bar_id)
                    open_hours += 1
    }
  end

  def self.assign_hour(open_hours, today, pop, bar_id)
    open_hours -= 12 if open_hours > 23
    day = Day.where(bar_id: bar_id, day: today, hour: open_hours)
    day.first.attributes = { :popularity => pop }
    day.first.save
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :bar
  belongs_to :user, dependent: :destroy

  validates :user_id, uniqueness: { scope: :bar_id }
  validates :bar, presence: true
  validates :description, presence: true
  validates :rating, presence: true
  validates :rating, numericality: {
    greater_than: 0,
    less_than_or_equal_to: 10 }

  def self.rating(comments)
    total_rating = 0
    rating_num = (comments.size)
    if (rating_num > 0)
      comments.each do |comment|
        total_rating += comment[:rating].to_f
      end
      bar_rating = (total_rating/ rating_num)
    else
      bar_rating = 0
    end
    return bar_rating
  end
end

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :bar
  validates_uniqueness_of :bar_id, scope: [:day, :hour]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bars
  has_many :comments

  devise(
    :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable)

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def authorize_admin!
    if current_user.nil? || !current_user.admin?
      flash[:notice] = "You are not authorized to view this resource."
      redirect_to root_path
    end
  end

  def after_sign_in_path_for(_resource)
    bars_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(
        :username, :email, :password, :password_confirmation
      )
    end

    devise_parameter_sanitizer.for(:account_update) << [:username]

    devise_parameter_sanitizer.for(:sign_in) do |u|
      u.permit(:username, :email, :password, :remember_me)
    end
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user!, only: [:edit, :update]
  before_action :authorize_admin!, only: [:destroy]

  def upvote
    @bar = Bar.find(params[:id])
    @bar.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @bar = Bar.find(params[:id])
    @bar.downvote_by current_user
    redirect_to :back
  end

  def index
    @bars = Bar.page(params[:page])
    Bar.popular_times(@bars)
    time = Time.new
    @day = time.strftime('%A')+"\'s"
    @hour = time.strftime('%I-%p')
    @hour_now = Time.now.strftime("%H")
    @day_now = Time.now.strftime("%A")
  end

  def show
    @bar = Bar.find(params[:id])
    @comments = @bar.comments
    @bar_rating = Comment.rating(@comments)
  end

  def new
    @bar = Bar.new
  end

  def edit
    @bar = Bar.find(params[:id])
  end

  def create
    @bar = Bar.new(bar_params)
    @bar.user = current_user
    create_query
    if @bar.save
      flash[:notice] = "BAR added successfully"
      redirect_to bar_path(@bar)
    else
      flash.now[:errors] = @bar.errors.full_messages.join(". ")
      render :new
    end
  end

  def create_query
    @query = "http://www.google.com/search?q="
    @query << "#{@bar.name}+#{@bar.location}&num=10"
    @bar.popular_query = @query.gsub!(/\s+/, "+")
  end

  def update
    @bar = Bar.find(params[:id])

    if @bar.update_attributes(bar_params)
      flash[:notice] = 'BAR updated successfully'
      redirect_to bar_path(@bar)
    else
      flash.now[:error] = @bar.errors.full_messages.join(". ")
      render :edit
    end
  end

  private

  def bar_params
    params.require(:bar).permit(
      :name, :location, :address)
  end

  def authorize_user!
    user = Bar.find(params[:id]).user
    unless current_user == user || current_user.admin?
      flash[:alert] = "You Are Not Authorized To View The Page"
      redirect_to after_sign_in_path_for(current_user)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [
    :new, :create, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def new
    @bar = Bar.find(params[:bar_id])
    @user = current_user
    @comment = Comment.new
  end

  def edit
    @bar = Bar.find(params[:bar_id])
    @user = current_user
    @comment = Comment.find(params[:id])
  end

  def create
    @bar = Bar.find(params[:bar_id])
    @user = current_user
    @comment = @bar.comments.new(comment_params)
    @comment.user = @user
    if @comment.save
      flash[:notice] = "Comment added successfully"
      redirect_to bar_path(@bar)
    else
      flash.now[:errors] = @comment.errors.full_messages.join(". ")
      render :new
    end
  end

  def update
    @bar = Bar.find(params[:bar_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)

    if @comment.save
      flash[:notice] = 'Comment updated successfully'
      redirect_to bar_path(@comment.bar)
    else
      flash.now[:error] = @comment.errors.full_messages.join(". ")
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    bar = @comment.bar
    @comment.destroy

    redirect_to bar_path(bar), notice: "Comment Destroyed!"
  end

  private

  def comment_params
    params.require(:comment).permit(:description, :rating, :user, :bar)
  end

  def authorize_user!
    user = Comment.find(params[:id]).user
    unless current_user == user || current_user.admin?
      flash[:alert] = "You Are Not Authorized To View The Page"
      redirect_to after_sign_in_path_for(current_user)
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render layout: 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bars/_comment.html.erb
<div class="container">
<div class="row">
<div class="col-sm-12">
<h3>Comments</h3>
</div><!-- /col-sm-12 -->
</div><!-- /row -->
<% num = 0 %>
<% @comments.each do |comment| %>
 <% num += 1 %>

<div class="row">
<div class="col-sm-1">
<div class="thumbnail">
<img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
</div><!-- /thumbnail -->
</div><!-- /col-sm-1 -->

<div class="col-sm-5">
<div class="panel panel-default">
<div class="panel-heading">
<strong><%= comment.user.username %></strong> <span class="text-muted"><%= comment.created_at %></span>
</div>
<div class="panel-body">
<%= comment.description %>
</div><!-- /panel-body -->
</div><!-- /panel panel-default -->
</div><!-- /col-sm-5 -->
  <% if num > 1 %>
    <% num = 0 %>
</div><!-- /row -->
<br>
  <% end %>

<% end %>

</div><!-- /container -->

app/views/bars/_form.html.erb
<div class = "col-md-3">
<div class="form-style">
<%= simple_form_for @bar do |f| %>
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :address %>
<% if @bar.persisted? %>
  <%= f.submit 'Update Bar', class: "btn btn-default" %>
  <% else %>
    <%= f.submit 'Add Bar', class: "btn btn-default" %>
<% end %>
  <% end %>

<%= button_to 'Cancel', bars_path, method: :get, class: "btn btn-default" %>
</div>
</div>

app/views/bars/_popbars.html.erb
 <%= stylesheet_link_tag    "bars-style" %>
 <%= javascript_include_tag 'jquery.barfiller.js' %>
      <div id="bar1" class="barfiller">
      <div class="tipWrap">
        <span class="tip"></span>
      </div>
        <span class="fill" data-percentage="12"></span>
    </div>


</div>



<script type="text/javascript">
$(document).ready(function(){
  $('#bar1').barfiller({ barColor: '#fc6' });
  $('#bar2').barfiller();
  $('#bar3').barfiller({ barColor: '#fc6' });


});
</script>

app/views/bars/edit.html.erb
<h1>Update BAR Form</h1>

<%= render 'form' %>
<%= link_to 'Cancel', bar_path(@bar) %>

app/views/bars/index.html.erb
<body class="appear-animate">
  <div class="page-loader">
    <div class="loader">Loading...</div>
  </div>
  <div class="page" id="top">
    <section class="home-section parallax-2" id="home">
      <div class="js-height-full">
        <div class="home-content">
          <div class="home-text">
            <div class="row">
              <div class="col-sm-6">
                <h1 class="hs-line-2 font-alt mb-80 mb-xs-30 mt-50 mt-sm-0">
                  Bar Hopping In Boston
                </h1>
                <div class="mt-140 mt-lg-80 mb-140 mb-lg-80">
                  <div class="banner-content">
                    <div class="local-scroll">
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-sm-6 banner-image wow fadeInUp" data-wow-duration="1.2s">
                <%= image_tag("bar_banner.png") %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>


  <div class="row">
    <h1 class="hs-line-8 font-alt mb-80 mb-xs-30 mt-50 mt-sm-0">
      <div class="col-md-4 align-center">
        Bar Crowd: <%= @day %> <br> @ <%= @hour %>
      </div>
      <div class="col-md-4 align-center">
        Bar
      </div>
      <div class="col-md-4 align-center">
        BarHopper's Likes
      </div>
    </h1>
  </div>

  <% @bars.each do |bar| %>
    <% pop_time = Day.where(bar_id: bar.id, day: @day_now, hour: @hour_now).select(:popularity).take %>
      <div class="row">
        <div class="barh1 col-md-4" id="pop-filler">
          <div id="<%= bar.bar_img %>" class="barfiller">
            <div class="tipWrap">
              <span class="tip"></span>
            </div>
            <span class="fill" data-percentage="<%= pop_time.popularity %>" ></span>
          </div>
        </div>
        <div class="bahr1 col-md-4 align-center" id="bar-name">
          <ul class="barh1">
            <li><%= link_to bar.name, bar_path(bar)%> - <%=bar.location%></li>
          </ul>
        </div>
        <div class="bahr1 col-md-4 align-center" id="bar-name">
          <ul class="barh1">
            <%= link_to image_tag("thumbs_up.png", width: 30, height: 30), like_bar_path(bar), method: :put, id: "upvote" %> <%= bar.upvotes_score %> <%= link_to image_tag("thumbs_down.png", width: 30, height: 30), dislike_bar_path(bar), method: :put, id: "downvote" %> <%= bar.downvotes_score %>
          </ul>
        </div>



        <%= javascript_include_tag "jquery.barfiller" %>
        <script type="text/javascript">

          $(document).ready(function(){

          $('#<%= bar.bar_img %>').barfiller();


          });

        </script>
      </div>
  <% end %>
    <%= link_to "Add bar", new_bar_path %>
</body>

app/views/bars/new.html.erb
<div class="section-title">
  Help out your fellow BarHoppers, let them know where to go..
</div>

<%= render 'form' %>

app/views/bars/show.html.erb
<br>
<br>
<div class="side-panel-is-left">
<h1 class="hs-line-9"> <%= @bar.name %></h1>
<h1 class="hs-line-8">
<p>
  <%= @bar.location %>
  <br>
  <%= @bar.address %>
</p>
</h1>
  <div class ="hs-line-15 highlight">
    <h1 class="hs-line-8"> User Rating: </h1>&nbsp&nbsp<%= @bar_rating %>
    </div>
<br>
<br>
  <% if current_user %>
   <%= link_to "Post Comment", new_bar_comment_path(@bar, @comment) %> &nbsp&nbsp&nbsp
   <%= link_to "Back to Bars", bars_path %>
      <% end %>
      <% if (@bar.user == current_user) %>
        <%= link_to "Update", edit_bar_path %>
      <% end %>


</div>
<%= render "comment" %>

app/views/comments/_form.html.erb
<div class="align-center">
<%= form_for [@bar, @comment] do |f| %>
  <%= f.label :description%>
  <%= f.text_field :description %>

  <%= f.label :rating %>
  <%= f.text_field :rating %>


  <% if @comment.persisted? %>
    <%= f.submit "Update Comment" %>
  <% else %>
    <%= f.submit "Add Comment", {:class=>"btn btn-default"}%>
    <%= link_to "Cancel", bar_path(@bar), {:class=>"btn btn-default"} %>
  <% end %>
<% end %>


</div>

app/views/comments/edit.html.erb
<h1>Update Comment Form</h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<br>
<h1 class="hs-line-8 align-center">Let your fellow BarHopper's know what you think!</h1>
<br>
<br>
<br>

<%= render 'form' %>

app/views/layouts/_flash.html.erb
<div class="row">
  <% flash.each do |key, value| %>
    <div class="alert <%= key %>">
      <%= value %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<%= stylesheet_link_tag 'application' %>
<%= javascript_include_tag 'jquery.barfiller.js' %>
<%= javascript_include_tag 'jquery-1.11.2.min.js' %>
<%= javascript_include_tag 'jquery.easing.1.3.js' %>

<div class="fixed">
    <div class="topbar">
        <nav class="main-nav dark transparent stick-fixed">
            <div class="full-wrapper relative clearfix">
                <div class="nav-logo-wrap local-scroll">
                    <a href="/" class="logo"> BarHopper
                    </a>
                </div>
                <div class="mobile-nav">
                    <i class="fa fa-bars"></i>
                </div>
                <div class="inner-nav desktop-nav">
                    <ul class="clearlist scroll-nav local-scroll">
                        <li class="active">
                        <% if current_user %>
                            <li id="active"><%= link_to 'Settings', edit_user_registration_path %></li>
                            <li id="active"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
                        <% else %>
                            <li id="active"><%= link_to "Sign In", new_user_session_path %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Bar Hopper" %></title>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="welcome-wrapper">
      <nav class="row full-width top-bar welcome-top-bar fixed" data-topbar role="navigation">
        <%= render "layouts/header" %>
      </nav>
    </div>
<div class="home-content" id="fflash">

 <%= render "layouts/flash" %>
 </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Bar Hopper" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="welcome-wrapper">
      <nav class="row full-width top-bar welcome-top-bar fixed" data-topbar role="navigation">
      </nav>
      <%= render "layouts/header" %>
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>BarHopper</title>
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta charset="utf-8">
        <meta name="Tim O'Bara" content="Tim O'Bara">

        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

       <%= stylesheet_link_tag 'application' %>



    </head>
    <body class="appear-animate">

        <!-- Page Loader -->
        <div class="page-loader">
            <div class="loader">Loading...
            </div>
        </div>
        <!-- End Page Loader -->

        <!-- Page Wrap -->
         <div class="page" id="top">

            <!-- Home Section -->
            <section class="home-section bg-dark-alfa-30 parallax-2" data-background="/assets/black.png" id="home">
                <div class="js-height-full">

                    <!-- Hero Content -->
                    <div class="home-content">
                        <div class="home-text">


                    <div class="row">

                        <div class="col-sm-6">
                            <h1 class="hs-line-1 font-alt mb-80 mb-xs-30 mt-50 mt-sm-0">

              </h1>
                            <div class="mt-140 mt-lg-80 mb-140 mb-lg-80">
                                <div class="banner-content">
                                    <h3 class="banner-heading font-alt">Boston, MA</h3>
                                    <div class="local-scroll">
                                        <%= link_to "Enter", bars_path %>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="col-sm-6 banner-image wow fadeInUp" data-wow-duration="1.2s">

                            <%= image_tag("beer.png") %>
                        </div>

                    </div>
              </div>
                </div>
                </div>
            </section>
        </div>
        <!-- End Page Wrap -->


        <!-- JS -->


        <%= javascript_include_tag 'application.js' %> <script type="text/javascript"> </script>
 </script>
        <!--[if lt IE 10]><script type="text/javascript" src="js/placeholder.js"></script><![endif]-->

    </body>
</html>